config/routes.rb
Rails.application.routes.draw do
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  mount ImgUploader::UploadEndpoint => '/imgs/upload'

  resources :imgs
  resources :tags
  resources :users

  get    'signup' => 'users#new'
  get    'about'  => 'pages#about'
  get    'login',  to: 'sessions#new'
  post   'login',  to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  root 'pages#root'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/img.rb
class Img < ApplicationRecord
  include ImgUploader[:image]
end

app/models/img_uploader.rb
class ImgUploader < Shrine
end

app/models/tag.rb
class Tag < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token

  before_save { self.email = email.downcase }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name,  presence: true, length: { maximum: 50 }

  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  validates :password, presence: true, length: { minimum: 6 }

  has_secure_password

  # _dw TODO refactor this once the task is done...
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  after_action :verify_authorized, except: :index
  # after_action :verify_policy_scoped, only: :index

  protect_from_forgery with: :exception

  include ApplicationHelper # _dw can I get rid of helpers once pundit?

private

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(request.referrer || root_path)
  end
end

app/controllers/imgs_controller.rb
class ImgsController < ApplicationController
  before_action :set_img, only: [:show, :edit, :update, :destroy]
  before_action :skip_authorization

  def index
    @imgs = Img.all
  end

  def show
  end

  def new
    @img = Img.new
  end

  def edit
  end

  def create
    @img = Img.new(img_params)

    respond_to do |format|
      if @img.save
        format.html { redirect_to @img, notice: 'Img was successfully created.' }
        format.json { render :show, status: :created, location: @img }
      else
        format.html { render :new }
        format.json { render json: @img.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @img.update(img_params)
        format.html { redirect_to @img, notice: 'Img was successfully updated.' }
        format.json { render :show, status: :ok, location: @img }
      else
        format.html { render :edit }
        format.json { render json: @img.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @img.destroy
    respond_to do |format|
      format.html { redirect_to imgs_url, notice: 'Img was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_img
      @img = Img.find(params[:id])
    end

    def img_params
      params.require(:img).permit(:image)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :skip_authorization
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :skip_authorization

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      flash[:notice] = "Welcome back, #{user.name}"
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      remember user
      redirect_to user
    else
      flash.now[:notice] = 'Invalid email/password combination'
      render :new
    end
  end

  def destroy
    log_out if logged_in?
    flash[:notice] = 'You have successfully logged out.'
    redirect_to root_url
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  def index
    @tags = Tag.all
  end

  def show
    authorize @tag
  end

  def new
    @tag = Tag.new
    authorize @tag
  end

  def edit
    authorize @tag
  end

  def create
    @tag = Tag.new(tag_params)
    authorize @tag

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    authorize @tag
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize @tag
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_url, notice: 'Tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_tag
      @tag = Tag.find(params[:id])
    end

    def tag_params
      params.require(:tag).permit(:title, :body)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :skip_authorization

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:email, :name, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def log_in(user)
   session[:user_id] = user.id
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def forget(user)
    current_user && user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end
end

app/views/imgs/_form.html.erb
<%= form_with(model: img, local: true) do |form| %>
  <% if img.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(img.errors.count, "error") %> prohibited this img from being saved:</h2>

      <ul>
      <% img.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/imgs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Imgs</h1>

<table>
  <thead>
    <tr>
      <th>Image data</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @imgs.each do |img| %>
      <tr>
        <td><%= img.image_data %></td>
        <td><%= link_to 'Show', img %></td>
        <td><%= link_to 'Edit', edit_img_path(img) %></td>
        <td><%= link_to 'Destroy', img, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Img', new_img_path %>

app/views/imgs/new.html.erb
<h1>New Img</h1>

<%= render 'form', img: @img %>

<%= link_to 'Back', imgs_path %>

app/views/imgs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Image data:</strong>
  <%= @img.image_data %>
</p>

<%= image_tag @img.image.url %>

<%= link_to 'Edit', edit_img_path(@img) %> |
<%= link_to 'Back', imgs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <%= render 'shared/layout/head' %>
  <body>
    <%= render 'shared/layout/header' %>
    <%= render 'shared/layout/flash' %>
    <%= yield %>
    <%= render 'shared/layout/scripts' %>
  </body>
</html>

app/views/learn/forms.html.erb
<h1>Forms</h1>
<p>I want to get better at learning about forms.</p>
<ul>
  <li>how forms work with events</li>
  <li>common form attributes</li>
  <li>how forms work with backbone</li>
  <li>how forms work with rails</li>
  <li>how to use forms when they don't look like forms</li>
</ul>

app/views/learn/index.html.erb
<h1>learnings</h1>
<p>Hello, this part of the farm is where I tinker with various parts of web development in an effort to better understand how these things work.</p>

app/views/pages/_head.html.erb
<% content_for :head do %>
  <title>fakefarm | Dave Woodall online</title>
<% end %>

<% content_for :stylesheets do %>
  <%= stylesheet_link_tag 'root' %>
<% end %>

app/views/pages/about.html.erb
<section class="l-container">
  <h1 class='h1'>About</h1>
  <div class="container">
    <p class="p">Fake farm is the digital playground of Dave Woodall. It is a Ruby on Rails app that houses a collection of random projects including... well nothing yet.</p>
  </div>
</section>

app/views/pages/root.html.erb
<div class="l-container-center">
  <div class="hot-tub">
    <%= image_tag 'https://d13yacurqjgara.cloudfront.net/users/137644/screenshots/1877532/hottub.png' %>
  </div>
  <h1 class="h5">Nothing to see here.</h1>
  <p class="p">A few years ago I started Fake Farm as a static site to practice front end pet projects. However, I recently decided to convert to a <a href="https://github.com/fakefarm/fakefarmapp">Ruby on Rails app</a>. </p>
    <p class='p'>
      Currently, I'm spending my time on the backend stuff (users, authentication, aws, new relic, etc) so there's not much to see right now. Feel free to visit my other placeholder domains, or my github.
    </p>
    <ul>
      <li class='p'><%= link_to 'dave.woodalls.me', 'http://dave.woodalls.me' %>
      </li>
      <li class='p'><%= link_to 'davewoodall.com', 'http://www.davewoodall.com' %>
      </li>
      <li class="p">
        <%= link_to 'github', 'http://www.github.com/fakefarm' %>
      </li>
    </ul>
    <%= image_tag 'face.svg' %>
</div>

app/views/shared/layout/_flash.html.erb
<% if notice %>
  <div class="notice">
    <%= notice %>
  </div>
<% end %>

app/views/shared/layout/_head.html.erb
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="description" content="Typically I rebuild my site once a year to practice what I've been learning. It's a way to experiment in my own place of the Internet. Thanks for stopping by!">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="Everything begins with the creator" />
  <meta property="og:description" content="Typically I rebuild my site once a year to practice what I've been learning. It's a way to experiment in my own place of the Internet. Thanks for stopping by!">
  <meta name="keywords" content="dave woodall fake farm leavelist fakefarm" />
  <meta name="author" content="dave woodall wwwoodall fake farm" />
  <meta property="og:url" content="http://www.fakefarm.com">
  <meta property="og:image" content="https://d13yacurqjgara.cloudfront.net/users/137644/screenshots/1628150/bird.jpg">
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <link href="https://fonts.googleapis.com/css?family=Crimson+Text:400i,600|Open+Sans" rel="stylesheet">
  <%= yield :stylesheets %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <% if content_for?(:head) %>
    <%= yield :head %>
  <% else %>
    <title>Fake Farm | by Dave Woodall</title>
  <% end %>
</head>

app/views/shared/layout/_header.html.erb
<header class='header'>
  <%= render 'shared/layout/header/logo_area' %>
  <%#= render 'shared/layout/header/nav' %>
</header>

app/views/shared/layout/_scripts.html.erb
<!-- _dw make sure to update fakefarm UI- google number -->
<script>
  (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
  function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
  e=o.createElement(i);r=o.getElementsByTagName(i)[0];
  e.src='//www.google-analytics.com/analytics.js';
  r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
  ga('create','UA-40303853-1','auto');ga('send','pageview');
</script>

app/views/shared/layout/header/_nav.html.erb
<nav class='main-nav'>
  <ul class='nav-links'>
    <li><%= link_to 'specs', jasmine_rails_path %></li>
    <li><%= link_to 'style guide', '/assets/styleguide' %></li>
    <li><%= link_to 'about', about_path %></li>
    <% if logged_in? %>
      <li>Hello, <%= current_user.name %></li>
      <li><%= link_to 'Log out', logout_path, method: :delete %></li>
      <li><%= link_to 'Profile', current_user %></li>
    <% else %>
      <li><%= link_to 'Join', new_user_path %></li>
      <li><%= link_to 'Log in', login_path %></li>
    <% end %>
  </ul>
</nav>

app/views/tags/_form.html.erb
<%= form_with(model: tag, local: true) do |form| %>
  <% if tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% tag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :tag_title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, id: :tag_body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<h1>Editing Tag</h1>

<%= render 'form', tag: @tag %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<h1>Tags</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tags.each do |tag| %>
      <tr>
        <td><%= tag.title %></td>
        <td><%= tag.body %></td>
        <td><%= link_to 'Show', tag %></td>
        <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
        <td><%= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tag', new_tag_path %>

app/views/tags/new.html.erb
<h1>New Tag</h1>

<%= render 'form', tag: @tag %>

<%= link_to 'Back', tags_path %>

app/views/tags/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @tag.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @tag.body %>
</p>

<%= link_to 'Edit', edit_tag_path(@tag) %> |
<%= link_to 'Back', tags_path %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :user_email %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :user_name %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password, id: :user_password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, id: :user_password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>Join the Farm!</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>